### ISSUE TITLE
Categories page still seems a bit odd

### ISSUE THREAD

**Issue by scaleoutsean** [PandaSekh/Jekyll-YAMT#19]
I saw there was a fix for #7 but couldn't get categories to show without two additional changes:
a) Change pages as below
b) Add header and footer to `_layouts/categories.html` (without it categories HTML is displayed, but without header & footer)

```
pages:
  - {name: 'About', url: 'about.html'}
  - {name: 'Archive', url: 'archive.html'}
  - {name: 'Categories', url: '/categories/'}
```

These are hacks and I don't even know if they're necessary (maybe the fix for #7 was complete, it's possible that minor modifications I made for the site broke it), but if they're not feel free to close this issue. If they are hope you can use them to further improve that fix. I built my site by semi-manually to make minor changes, so it may be different from when it's cloned directly.

**Comment by PandaSekh** [comment]
> couldn't get categories to show  

Where? Under posts or in the menu? To make them appear under the posts you have to set as `true` a setting in the `settings.yml` file. Now, onto your fixes:  
You changed your pages.yml file and as an url for the categories you used "/categories/", but this is the same as writing "categories.html" (or maybe it's bad as Jekyll can't know for sure your categories page is at that url. I don't know, I'll test this). So I don't actually understand if there was a problem in that file or not, honestly.

Then, you added header and footer to the categories.html file in the layouts folder, but that file already inherits the default layout, which includes the header and the footer, so you shouldn't have to add them again in that file.  

As you can see from the demo, the categories works just fine, so I think that this was a problem on your end, maybe you forgot to copy a file or something else. If you have to make minor changes I would suggest to clone the entire project and then make changes on that clone, instead of copy-pasting part by part as that might break something.  

If you still have problem let me know

**Comment by scaleoutsean** [comment]
Thanks for the response. It is likely the problem is a result of my changes, I just thought to ask you to recheck if the fix is correct on your side. I know the site is functioning correctly but I looked at https://github.com/PandaSekh/Jekyll-YAMT/blob/master/_data/pages.yml and there is no categories in that file, that's the reason I asked.

Since the fix has no problem, let's close this issue (I don't expect that you should troubleshoot my non standard modifications). 🙂
